version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: java_patterns
      POSTGRES_USER: user
      POSTGRES_PASSWORD: my-secret-pw
    ports:
      - "5432:5432"

  java-patterns:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/java_patterns
      DB_USERNAME: user
      DB_PASSWORD: my-secret-pw
