services:
  api:
    image: spring-api
    container_name: spring-api
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - ./src:/api-app/src
    command: sh ./docker-entrypoint.sh
    ports:
      - 8080:8080

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/my_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
    restart: always

  db:
    image: mysql:latest
    container_name: mysql-db

    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    restart: always